In [1]:
import numpy as np

In [2]:
x = np.load('../tatanic_X_train.npy')
y = np.load('../tatanic_y_train.npy')

In [3]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=101)

In [4]:
x_train[0]

array([0.22334962, 0.01517579, 0.        , 1.        , 1.        ,
       0.        , 0.        , 0.        , 0.        , 1.        ,
       0.        , 0.        , 0.        , 0.        , 1.        ,
       0.        , 0.        , 0.        , 1.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        ])

In [5]:
y_train[:10]

array([0., 1., 1., 1., 0., 0., 1., 1., 0., 1.])

In [6]:
from sklearn.ensemble import RandomForestClassifier
eclf = RandomForestClassifier(n_estimators=100, max_features=2, n_jobs=7, oob_score=True)

In [7]:
from sklearn.model_selection import cross_val_score
cross_val_score(eclf, x_train, y_train, cv=5).mean()

0.8071684587813621

In [8]:
params = {'n_estimators':[10,20,30,50,100],
         'max_features':[1,2,3,4,5,6,7,10,15,20,25,len(x[0])]}

In [9]:
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(estimator = eclf, param_grid = params, cv=5)
grid.fit(x_train, y_train)
predictions = grid.predict(x_test)

C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:458: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:463: RuntimeWarning: invalid value encountered in true_divide
  predictions[k].sum(axis=1)[:, np.newaxis])
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:458: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:463: RuntimeWarning: invalid value encountered in true_divide
  predictions[k].sum(axis=1)[:, np.newaxis])
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:458: UserWarning: Some inputs do not have OOB scores. This probably means t

C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:458: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:463: RuntimeWarning: invalid value encountered in true_divide
  predictions[k].sum(axis=1)[:, np.newaxis])
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:458: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:463: RuntimeWarning: invalid value encountered in true_divide
  predictions[k].sum(axis=1)[:, np.newaxis])
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:458: UserWarning: Some inputs do not have OOB scores. This probably means t

C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:458: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:463: RuntimeWarning: invalid value encountered in true_divide
  predictions[k].sum(axis=1)[:, np.newaxis])
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:458: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:463: RuntimeWarning: invalid value encountered in true_divide
  predictions[k].sum(axis=1)[:, np.newaxis])
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:458: UserWarning: Some inputs do not have OOB scores. This probably means t

C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:458: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:463: RuntimeWarning: invalid value encountered in true_divide
  predictions[k].sum(axis=1)[:, np.newaxis])
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:458: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:463: RuntimeWarning: invalid value encountered in true_divide
  predictions[k].sum(axis=1)[:, np.newaxis])
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:458: UserWarning: Some inputs do not have OOB scores. This probably means t

In [10]:
grid.best_score_

0.8215434083601286

In [11]:
grid.best_params_

{'max_features': 20, 'n_estimators': 100}

In [12]:
grid.best_estimator_.oob_score_

0.8022508038585209

In [13]:
grid.best_estimator_

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features=20, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=7,
            oob_score=True, random_state=None, verbose=0, warm_start=False)

In [14]:
grid.score(x_test, y_test)

0.850187265917603

In [15]:
from sklearn.metrics import confusion_matrix,classification_report

In [16]:
confusion_matrix(y_test, predictions)

array([[148,  15],
       [ 25,  79]], dtype=int64)

In [17]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

         0.0       0.86      0.91      0.88       163
         1.0       0.84      0.76      0.80       104

   micro avg       0.85      0.85      0.85       267
   macro avg       0.85      0.83      0.84       267
weighted avg       0.85      0.85      0.85       267



In [18]:
btree = RandomForestClassifier(max_features=20, n_estimators=20)

In [19]:
btree.fit(x_train, y_train)
btree.score(x_test, y_test)

0.846441947565543

In [20]:
btree.feature_importances_

array([0.21741839, 0.22640719, 0.01837925, 0.07601545, 0.1513134 ,
       0.04153384, 0.01089097, 0.00951916, 0.0061697 , 0.01488095,
       0.00297379, 0.00053069, 0.00289344, 0.01343283, 0.00791964,
       0.14253419, 0.0043323 , 0.00719942, 0.01220438, 0.00215614,
       0.00301352, 0.00560778, 0.0103043 , 0.01025337, 0.00118367,
       0.00093222, 0.        ])