In [1]:
import numpy as np

In [2]:
elements = ['one', 'two', 'three']
weights = [0.2, 0.3, 0.5]

from numpy.random import choice
print(choice(elements))
print(choice(elements, size=10, replace=True, p=weights))

In [3]:
x = np.load('../tatanic_X_train.npy')
y = np.load('../tatanic_y_train.npy')

In [4]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=101)

In [5]:
x_train[:2]

array([[0.22334962, 0.01517579, 0.        , 1.        , 1.        ,
        0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 0.        , 0.        , 1.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.22334962, 0.04489301, 0.11111111, 0.5       , 1.        ,
        0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 0.        , 0.        , 1.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ]])

In [6]:
y_train[:10]

array([0., 1., 1., 1., 0., 0., 1., 1., 0., 1.])

In [7]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier

In [8]:
eclf = AdaBoostClassifier(base_estimator = DecisionTreeClassifier(max_depth=2), n_estimators=500, learning_rate=0.1)

In [9]:
from sklearn.model_selection import cross_val_score
cross_val_score(eclf, x_train, y_train, cv=5).mean()

0.8023041474654379

In [10]:
from sklearn.tree import DecisionTreeClassifier
DecisionTreeClassifier()

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [11]:
AdaBoostClassifier()

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=50, random_state=None)

In [12]:
params = {"base_estimator__criterion" : ["gini", "entropy"],
          "base_estimator__max_features" : [7,8,],
          "base_estimator__max_depth" : [1,2,3,4,5],
          "n_estimators": [23,24, 25, 26, 27],
          "learning_rate": [0.4, 0.45, 0.5, 0.55, 0.6]
         }

In [13]:
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(estimator=eclf, param_grid=params, cv=5, n_jobs=7)
grid.fit(x_train, y_train)
predictions = grid.predict(x_test)

C:\Users\user\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


In [14]:
grid.best_score_

0.815112540192926

In [15]:
grid.best_params_

{'base_estimator__criterion': 'gini',
 'base_estimator__max_depth': 2,
 'base_estimator__max_features': 7,
 'learning_rate': 0.55,
 'n_estimators': 26}

In [16]:
grid.best_estimator_.feature_importances_

array([0.233949  , 0.17871702, 0.05844427, 0.0383103 , 0.08064658,
       0.0759817 , 0.0720715 , 0.00085726, 0.04644996, 0.00718003,
       0.        , 0.02345472, 0.00798782, 0.0433523 , 0.00820649,
       0.02261453, 0.        , 0.01184501, 0.02964591, 0.00360907,
       0.02634804, 0.        , 0.01452056, 0.00276306, 0.        ,
       0.00539203, 0.00765283])

In [17]:
grid.score(x_train, y_train)

0.8569131832797428

In [18]:
grid.score(x_test, y_test)

0.8164794007490637

In [19]:
from sklearn.metrics import confusion_matrix,classification_report

In [20]:
confusion_matrix(y_test, predictions)

array([[145,  18],
       [ 31,  73]], dtype=int64)

In [21]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

         0.0       0.82      0.89      0.86       163
         1.0       0.80      0.70      0.75       104

   micro avg       0.82      0.82      0.82       267
   macro avg       0.81      0.80      0.80       267
weighted avg       0.82      0.82      0.81       267

